apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: gitea-http
      port: 3000